// Identify object
export const IDENTIFY_OBJECT_REQUEST = "IDENTIFY_OBJECT_REQUEST";
export const IDENTIFY_OBJECT_SUCCESS = "IDENTIFY_OBJECT_SUCCESS";
export const IDENTIFY_OBJECT_FAIL = "IDENTIFY_OBJECT_FAIL";
